### ISSUE TITLE
Possible conflict with old and new viewpoint software?

### ISSUE THREAD

**Issue by BaylorSci** [francoiskroll/FramebyFrame#2]
I'm trying to use your package with data obtained on a viewpoint behavioral unit back in 2020 ish. Since then, the software has been updated (May 2023) and i am wondering if this is the cause of the issue. When i try to load the data, i get the following error:

 >>> Sorting RAW .xls files in directory reexport-default/Plate2/                        
>>>  EXPERIMENT Plate2                         
 >>>  FORMATTING CHECK                    
 >>>  Selecting column abstime at position 1                      
 >>>  Selecting column time at position 2                          
>>>  Selecting column type at position 4                          
>>>  Selecting column location at position 5                      
>>>  Selecting column data1 at position 6                         
>>>  Detected * 0 * - well plate
In addition: Warning message:In min(nchar(fi1$location)) :  no non-missing arguments to min; returning Inf

I've emailed the two files, but i thought i would also put this here incase anyway else runs into this issue.

**Comment by francoiskroll** [comment]
After chatting by email, the issue was that the experiment was in Tracking mode (X/Y coordinates over time), not Quantization (pixel counts over time). FramebyFrame expects pixel counts over time.
