### ISSUE TITLE
Github refuses installation without PAT

### ISSUE THREAD

**Issue by zeou1** [francoiskroll/FramebyFrame#3]
Hi Francois,

I tried to install the package in R using the instruction in the README and it came back with the error: 

> Using GitHub PAT from the git credential store.
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 401.
  Bad credentials
  Rate limit remaining: 57/60
  Rate limit reset at: 2024-05-14 15:46:44 UTC

I was able to download the package by creating my own PAT and add it to the `auth_token` argument in `install_github`. Consider adding that in the instruction so other people won't have the same issue as me.

**Comment by francoiskroll** [comment]
Hi Ze – Thanks for raising the issue!

Sorry, I tried uninstalling & installing again in a new project but I can't reproduce the issue. Maybe my PAT is recorded somewhere? I don't remember doing something like this though, and `Sys.getenv("GITHUB_PAT")` (from [here](https://stackoverflow.com/questions/70908295/failed-to-install-unknown-package-from-github)) returns `""` for me. I'll try on a different computer when I have the occasion!

Don't hesitate if you run into issues or have feedback about the package
